version: '3.7'
services:
  redis:
    image: redislabs/redistimeseries
    container_name: redistimeseries_server
    command: redis-server --appendonly yes --loadmodule /usr/lib/redis/modules/redistimeseries.so
    ports:
      - 56379:6379
    volumes:
      - ./db/redis-volume:/data
    restart: unless-stopped
  redisclient:
    build:
      context: build/.
      dockerfile: Dockerfile
    container_name: redistimeseries_client
    # command: python3 /app/main.py
    # volumes:
    #   - ./app:/app
